### ISSUE TITLE
Add ability to return covariance matrices from eigenvalue analysis functions.

### ISSUE THREAD

**Issue by willjbrown88** [gracecox/MagPy#5]
In `magpysv.denoise` there are two versions of the eigenvalue_analysis, it would be useful if one or both could optionally return the covariance matrices associated with the eigenanalysis.

I think this is a simple addition to the returns of the usual `denoise.eigenvalue_analysis()`, and I think the method `sklearn.decomposition.get_covariance()` is equivalent for the other `denoise.eigenvalue_analysis_impute()`. The latter would need some testing I expect.

**Comment by gracecox** [comment]
Covariance matrix now returned by magpysv.denoise.eigenvalue_analysis()
